question_data = [
	{"category": "Entertainment: Video Games",
	 "type": "boolean", "difficulty": "easy",
	 "question": "Peter Molyneux was the founder of Bullfrog Productions.",
	 "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"category": "General Knowledge",
	 "type": "boolean", "difficulty": "easy",
	 "question": "The Great Wall of China is visible from the moon.",
	 "correct_answer": "False",
	 "incorrect_answers": ["True"]},
	{"category": "Entertainment: Video Games",
	 "type": "boolean", "difficulty": "easy",
	 "question": "The song 'Megalovania' by Toby Fox made its third appearance in the 2015 RPG 'Undertale'.",
	 "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"category": "Entertainment: Film",
	 "type": "boolean", "difficulty": "easy",
	 "question": "The movie 'The Nightmare before Christmas' was all done with physical objects.",
	 "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"category": "Entertainment: Video Games",
	 "type": "boolean", "difficulty": "easy",
	 "question": "English new wave musician Gary Numan founded the video game development company Facepunch Studios in March 2009.",
	 "correct_answer": "False",
	 "incorrect_answers": ["True"]},
	{"category": "Entertainment: Music",
	 "type": "boolean", "difficulty": "easy",
	 "question": "The music video to The Buggle's 'Video Killed the Radio Star' was the first music video to broadcast on MTV.",
	 "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"category": "General Knowledge",
	 "type": "boolean", "difficulty": "easy",
	 "question": "Gumbo is a stew that originated in Louisiana.",
	 "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"category": "Geography",
	 "type": "boolean", "difficulty": "easy",
	 "question": "Vatican City is a country.",
	 "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"category": "Entertainment: Music",
	 "type": "boolean", "difficulty": "easy",
	 "question": "Eurobeat is primarily an Italian genre of music.",
	 "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"category": "Entertainment: Video Games",
	 "type": "boolean", "difficulty": "easy",
	 "question": "'Undertale' is an RPG created by Toby Fox and released in 2015.",
	 "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"category": "Entertainment: Video Games",
	 "type": "boolean", "difficulty": "easy",
	 "question": "Faust is a playable character in 'Guilty Gear Xrd Revelator'.",
	 "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"category": "Science: Mathematics",
	 "type": "boolean", "difficulty": "easy",
	 "question": "The 'Squaring the Circle' problem is solvable.",
	 "correct_answer": "False",
	 "incorrect_answers": ["True"]},
	{"category": "Entertainment: Video Games",
	 "type": "boolean", "difficulty": "easy",
	 "question": "Niko Bellic is the protagonist of Grand Theft Auto IV.",
	 "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"category": "Science: Computers",
	 "type": "boolean", "difficulty": "easy",
	 "question": "RAM stands for Random Access Memory.",
	 "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"category": "General Knowledge",
	 "type": "boolean", "difficulty": "easy",
	 "question": "A scientific study on peanuts in bars found traces of over 100 unique specimens of urine.",
	 "correct_answer": "False",
	 "incorrect_answers": ["True"]},
	{"category": "Entertainment: Video Games",
	 "type": "boolean", "difficulty": "easy",
	 "question": "In 'Sonic Adventure', you are able to transform into Super Sonic at will after completing the main story.",
	 "correct_answer": "False",
	 "incorrect_answers": ["True"]},
	{"category": "General Knowledge",
	 "type": "boolean", "difficulty": "easy",
	 "question": "The color orange is named after the fruit.",
	 "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"category": "History",
	 "type": "boolean", "difficulty": "easy",
	 "question": "United States President John F. Kennedy was assassinated during his presidential motorcade in Atlanta, Georgia on November 22nd, 1963.",
	 "correct_answer": "False",
	 "incorrect_answers": ["True"]},
	{"category": "History",
	 "type": "boolean", "difficulty": "easy",
	 "question": "Adolf Hitler was a german soldier in World War I.",
	 "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"category": "Entertainment: Video Games",
	 "type": "boolean", "difficulty": "easy",
	 "question": "In Team Fortress 2, being disguised as a scout or medic results in a speed boost.",
	 "correct_answer": "False",
	 "incorrect_answers": ["True"]},
	{"category": "Entertainment: Music",
	 "type": "boolean", "difficulty": "easy",
	 "question": "The alternative rock band, They Might Be Giants, released their album 'Flood' in 1990. ",
	 "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"category": "Entertainment: Japanese Anime & Manga",
	 "type": "boolean", "difficulty": "easy",
	 "question": "In Pok&eacute;mon, Ash's Pikachu refuses to go into a pokeball.",
	 "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"category": "General Knowledge",
	 "type": "boolean", "difficulty": "easy",
	 "question": "Adolf Hitler was born in Australia. ",
	 "correct_answer": "False",
	 "incorrect_answers": ["True"]},
	{"category": "Entertainment: Film",
	 "type": "boolean", "difficulty": "easy",
	 "question": "In the original Star Wars trilogy, Alec Guinness provided the voice for Darth Vader.",
	 "correct_answer": "False",
	 "incorrect_answers": ["True"]},
	{"category": "Entertainment: Japanese Anime & Manga",
	 "type": "boolean", "difficulty": "easy",
	 "question": "The name of the attack 'Kamehameha' in Dragon Ball Z was named after a famous king of Hawaii.",
	 "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"category": "Science: Computers",
	 "type": "boolean", "difficulty": "easy",
	 "question": "The Windows 7 operating system has six main editions.",
	 "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"category": "Entertainment: Video Games",
	 "type": "boolean", "difficulty": "easy",
	 "question": "In Pok&eacute;mon Sun and Moon, a male Salandit can evolve to a Salazzle.",
	 "correct_answer": "False",
	 "incorrect_answers": ["True"]},
	{"category": "Entertainment: Music",
	 "type": "boolean", "difficulty": "easy",
	 "question": "A Saxophone is a brass instrument.",
	 "correct_answer": "False",
	 "incorrect_answers": ["True"]},
	{"category": "Science & Nature",
	 "type": "boolean", "difficulty": "easy",
	 "question": "An exothermic reaction is a chemical reaction that releases energy by radiating electricity.",
	 "correct_answer": "False",
	 "incorrect_answers": ["True"]},
	{"category": "Geography",
	 "type": "boolean", "difficulty": "easy",
	 "question": "California is larger than Japan.",
	 "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"category": "Entertainment: Music",
	 "type": "boolean", "difficulty": "easy",
	 "question": "Daft Punk originated in France.",
	 "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"category": "Animals",
	 "type": "boolean", "difficulty": "easy",
	 "question": "Cats have whiskers under their legs.",
	 "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"category": "History",
	 "type": "boolean", "difficulty": "easy",
	 "question": "In World War ll, Great Britain used inflatable tanks on the ports of Great Britain to divert Hitler away from Normandy D-day landing.",
	 "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"category": "Entertainment: Film",
	 "type": "boolean", "difficulty": "easy",
	 "question": "'Minions' was released on the June 10th, 2015.",
	 "correct_answer": "False",
	 "incorrect_answers": ["True"]},
	{"category": "Entertainment: Video Games",
	 "type": "boolean", "difficulty": "easy",
	 "question": "In RuneScape, one must complete the 'Dragon Slayer' quest before equipping Rune Platelegs.",
	 "correct_answer": "False",
	 "incorrect_answers": ["True"]},
	{"category": "Entertainment: Music",
	 "type": "boolean", "difficulty": "easy",
	 "question": "Scatman John's real name was John Paul Larkin.",
	 "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"category": "Entertainment: Japanese Anime & Manga",
	 "type": "boolean", "difficulty": "easy",
	 "question": "Kiznaiver is an adaptation of a manga.",
	 "correct_answer": "False",
	 "incorrect_answers": ["True"]},
	{"category": "Entertainment: Video Games",
	 "type": "boolean", "difficulty": "easy",
	 "question": "In Heroes of the Storm, the Cursed Hollow map gimmick requires players to kill the undead to curse the enemy team.",
	 "correct_answer": "False",
	 "incorrect_answers": ["True"]},
	{"category": "Geography",
	 "type": "boolean", "difficulty": "easy",
	 "question": "Tokyo is the capital of Japan.",
	 "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"category": "Art",
	 "type": "boolean", "difficulty": "easy",
	 "question": "Leonardo da Vinci was not the creator of the Mona Lisa.",
	 "correct_answer": "False",
	 "incorrect_answers": ["True"]},
	{"category": "Entertainment: Cartoon & Animations",
	 "type": "boolean", "difficulty": "easy",
	 "question": "Waylon Smithers from 'The Simpsons' was originally black when he first appeared in the series.",
	 "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"category": "Entertainment: Video Games",
	 "type": "boolean", "difficulty": "easy",
	 "question": "'Metal Gear Solid 3: Snake Eater' was released in 2004.",
	 "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"category": "Geography",
	 "type": "boolean", "difficulty": "easy",
	 "question": "Hungary is the only country in the world beginning with H.",
	 "correct_answer": "False",
	 "incorrect_answers": ["True"]},
	{"category": "Geography",
	 "type": "boolean", "difficulty": "easy",
	 "question": "New Haven is the capital city of the state of Connecticut in the United States.",
	 "correct_answer": "False",
	 "incorrect_answers": ["True"]},
	{"category": "Politics",
	 "type": "boolean", "difficulty": "easy",
	 "question": "Former president Theodore Roosevelt (1900-1908)  ran for another term under the Progressive Party in 1912.",
	 "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"category": "Entertainment: Film",
	 "type": "boolean", "difficulty": "easy",
	 "question": " 'Foodfight!' earned less than $80,000 at box office.",
	 "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"category": "Science & Nature",
	 "type": "boolean", "difficulty": "easy",
	 "question": "Water always boils at 100°C, 212°F, 373.15K, no matter where you are.",
	 "correct_answer": "False",
	 "incorrect_answers": ["True"]},
	{"category": "Animals",
	 "type": "boolean", "difficulty": "easy",
	 "question": "Rabbits are carnivores.",
	 "correct_answer": "False",
	 "incorrect_answers": ["True"]},
	{"category": "Entertainment: Television",
	 "type": "boolean", "difficulty": "easy",
	 "question": "'The Simpsons' family is named after creator Matt Groening's real family.",
	 "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"category": "Animals",
	 "type": "boolean", "difficulty": "easy",
	 "question": "The freshwater amphibian, the Axolotl, can regrow it's limbs.",
	 "correct_answer": "True",
	 "incorrect_answers": ["False"]}
]
